### PR TITLE
Reinstatement of helm chart

### LINKED ISSUE #15: Revive Dask Helm ?
@beberg and I were chatting about reviving the helm-chat repo here rather than rely on the official helm repo.  Currently there is a lingering PR to update the dask helm chart but it's not getting much attention from helm devs to merge in : https://github.com/helm/charts/pull/12552

It's also worth noting that Jupyterhub maintains it's own helm chart:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s

cc @jacobtomlinson @mrocklin

### PR DESCRIPTION
**Pull request by jacobtomlinson**
The Kubernetes community are moving towards a more federated approach to charts (I know we started there but we are going back again!). 

It is now encouraged for projects to manage their own chart repositories and register them on https://hub.helm.sh/ as a central source for people to find charts. A helm chart repository is a web server consisting of a yaml file listing the versions and tgz archives containing the source config for those releases. As it is just static files it is easy to host these on GitHub Pages and I propose that we use this `gh-pages` branch of this repository to do so.

This PR does a few things:
- Pull in all changes to the chart that happened over on [helm/charts](https://github.com/helm/charts/tree/master/stable/dask) with git history.
- Add CI to lint the chart and deploy automatically on tags.
- Add chartpress and config to build and deploy the chart.
- Update installation instructions and add migration instructions.

Things that still need to happen before we can merge this and move back to managing our own chart repo:
- [x] I could also do with contributor access to this repo to ease setting things up (cc @mrocklin @TomAugspurger).
- [x] We should have a custom domain for the GitHub pages site for this repo to simplify installation instructions and allow us to potentially migrate easily in the future if we need to. I propose https://helm.dask.org. 
- [x] Add a deprecation notice to the chart on charts/stable (in the README and NOTES files).
- [x] Register our new chart repository with Helm Hub ([instructions](https://github.com/helm/hub/blob/master/Repositories.md)). 

Closes #15

### CODE REVIEW

**Comment by TomAugspurger** [comment]
Sorry for the delay.

>  I could also do with contributor access to this repo to ease setting things up (cc @mrocklin @TomAugspurger).

Done.

>  We should have a custom domain for the GitHub pages site for this repo to simplify installation instructions and allow us to potentially migrate easily in the future if we need to. I propose https://helm.dask.org.

Will the site be hosted on the `gh-pages` branch of this repository?

If so, @aterrel could you set up a DNS rule to have helm.dask.org point to this repo's gh-pages? It should be the same as the rules for ml.dask.org and gateway.dask.org.

>  Register our new chart repository with Helm Hub (instructions).

Is that done before or after merging this?

**Comment by aterrel** [comment]
I set up the dns rule.

**Comment by mrocklin** [comment]
Thanks Andy

**Comment by jacobtomlinson** [comment]
Thanks everyone. I'll continue pushing on this today. 

> Will the site be hosted on the gh-pages branch of this repository?

Yeah that's the plan.

> Is that done before or after merging this?

After. I'll put in a separate PR over int heir repo to do this.

**Comment by jacobtomlinson** [comment]
@TomAugspurger I don't seem to have enough permissions to update the domain of the GitHub Pages site in this repo or the build settings.

**Comment by TomAugspurger** [comment]
Sorry about that. Hopefully fixed now.

**Comment by jacobtomlinson** [comment]
Perfect thanks!

**Comment by jacobtomlinson** [comment]
Summary of changes this week.

- Added the rest of the CI config now that I have contributor access to set up keys.
- Raised PR for adding deprecation notices to existing charts helm/charts#18419.
- Raised PR to add the chart repo to Helm Hub helm/hub#171.
- Raised #19 to add a human readable front to the chart repo
- Written up this whole process in a [blog post](https://www.jacobtomlinson.co.uk/posts/2019/how-to-create-a-helm-chart-repository-with-chartpress-travis-ci-github-pages-and-jekyll/).

This is probably good to merge now.

**Comment by TomAugspurger** [comment]
Nice blog post!

I think you should merge whenever you're ready.

Will users need to change anything about their workflow, or does `helm install stable/dask` just point to our repository now?

**Comment by TomAugspurger** [comment]
Great, thanks. We'll also want to update
https://docs.dask.org/en/latest/setup/kubernetes.html.

**Comment by jacobtomlinson** [comment]
@TomAugspurger good point! Done in dask/dask#5539.

**Pull request merged**
