### PR TITLE
Explicitly set languages used

### PR DESCRIPTION
**Pull request by jacobtomlinson**
GitHub strangely reports this repo as moustache language. Just playing around to see if I can override that.

### CODE REVIEW

**Comment by consideRatio** [comment]
How did you learn about the kind of things you try out here? I'd love to help GitHub report this in a more reasonable way. I'm not sure though, what would be the right way to report Helm chart templates?

They are YAML files, but they are also helm chart templates / golang templates of YAML files, YAML files that represents k8s resources. So should the language be considered YAML, Helm chart templates, golang templates, Kubernetes resources, etc?

Is the detected languages by GitHub limited to a few fixed languages? If so, I guess perhaps helm/golang templates and k8s resources may not be something can specify, and we are left with the choice of YAML.

**Comment by jacobtomlinson** [comment]
GitHub uses this library https://github.com/github/linguist. They have a [list of languages here](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml).

I can't see anything related to k8s or helm in there though so went with YAML.

**Comment by jacobtomlinson** [comment]
Hrm this didn't quite have the desired effect. It is correctly ignoring the `ci` directory, but it's still reporting all the YAML as mustache.

**Comment by jacobtomlinson** [comment]
Oh I see, there is one `tpl` file in here that is identifying as mustache, and the YAML is being ignored. Let me raise another PR.

**Comment by jacobtomlinson** [comment]
Hooray 🎉
image

**Pull request merged**
