### PR TITLE
cleanup in gh-pages branch: remove broken release for dask-kubernetes-operator

### PR DESCRIPTION
**Pull request by consideRatio**
A release of the dask-kubernetes-operator Helm chart is malfunctional, and until its fixed I get regular error reports from artifact hub like this.

image

The reason was discussed in https://github.com/dask/helm-chart/pull/266#issuecomment-1125362071.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Apologies for the email noise.

Chartpress cannot publish unless there is at least one release already there, so I'm hesitant to remove this before resolving the issue as it will cause the release automation to fail.

I've raised dask/dask-kubernetes/issues/491 to track the problem, I would really appreciate your help there.

**Comment by consideRatio** [comment]
> Chartpress cannot publish unless there is at least one release already there

I thought it could, are you sure? If so I think its an unknown issue for https://github.com/jupyterhub/chartpress that would benefit from an issue report. Hmmm, I think maybe you would need to create a gh-pages branch or similar, but I don't think the index.yaml would need to be created ahead of time or have an entry for the chart ahead of time.

**Comment by jacobtomlinson** [comment]
> I thought it could, are you sure?

Yeah. I've raised https://github.com/jupyterhub/chartpress/issues/159 to track it.

**Comment by consideRatio** [comment]
> Yeah. I've raised https://github.com/jupyterhub/chartpress/issues/159 to track it.

Thank you for this great write-up!!!

**Comment by consideRatio** [comment]
The reason to hold off is resolved, merging this to put and end to the artificathub errors.

**Comment by jacobtomlinson** [comment]
Checking back in here, is this good to merge?

**Comment by consideRatio** [comment]
@jacobtomlinson depends. Are there non-broken releases of the `dask-kubernetes-operator` chart around now? If so, this PR should be updated to cleanup all of the broken and leave one or more non-broken releases.

**Comment by consideRatio** [comment]
I looked into that, and I concluded that 2022.7.0 was correct while 2022.5.0, 2022.5.1, 2022.5.2 was incorrect with `set-by-chartpress` tags.

**Comment by jacobtomlinson** [comment]
Many thanks for handling this @consideRatio

**Pull request merged**
