### PR TITLE
Pull jupyter notebook server to optional chart

### PR DESCRIPTION
**Pull request by mrocklin**
This now only installs a Jupyter notebook server if requested

    helm install ... --set jupyter.enabled=true

Default is false

### CODE REVIEW

**Comment by mrocklin** [comment]
cc @danielfrg for review if he has time

**Comment by mrocklin** [comment]
Hrm, alternatively I might consider reversing the order of the dependence, having `dask` be just dask and `dask-jupyter` depend on `dask` but add a jupyter notebook server.

**Comment by mrocklin** [comment]
Another, probably much simpler approach, is just to set `jupyter.replicas=0`

**Comment by danielfrg** [comment]
> Hrm, alternatively I might consider reversing the order of the dependence, having dask be just dask and dask-jupyter depend on dask but add a jupyter notebook server.

+1

> probably much simpler approach, is just to set jupyter.replicas=0

+1

**Comment by jacobtomlinson** [comment]
This change was made over in stable/dask and merged back in as part of #17.

**Pull request closed without merging**
